baseurl = "https://example.org"
title = "Personal Blog"
author = "Kristijan Petrovski"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "aether"
description = "aether Hugo theme for blogs"
bgimg = "/img/ignasi_pattern_s.png"
